name: Hello World
description: A description

inputs:
  who-to-greet:
    description: "Who to greet"
    required: true
    default: 'world'
outputs:
  time:
    description: "The current time"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
  - ${{ inputs.who-to-greet }}
