name: RunHelloWorld
on:
  push:
    paths:
    - hello-world-docker-action/**
  workflow_dispatch:
jobs:
  RunHelloWorld:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3.3.0
    - name: RunContainer
      id: RunContainer
      uses: ./hello-world-docker-action
      with:
        who-to-greet: "@immybo"
    - name: WriteOutput
      run: echo "${{ steps.RunContainer.outputs.time }}"
    
