name: GitHub Actions Demo
on:
  push:
    branches:
    - main
    paths-ignore: .github/**
  pull_request:
    branches:
    - main
  schedule:
    - cron: 15 6 * * SUN
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Triggering event name: $GITHUB_EVENT_NAME"
        echo "Branch or ref: $GITHUB_REF_NAME"
        echo "All files in the repository:"
        find
  
  
