name: Reuse other workflow
on:
  workflow_dispatch:
jobs:
  call-workflow:
    uses: immybo/ActionsFundamentals/.github/workflows/reusable.yml@main
    with:
      who-to-greet: immybo
  use-output:
    runs-on: ubuntu-latest
    needs: call-workflow
    steps:
    - run: echo "${{ needs.call-workflow.outputs.current-time }}"
    
